[package]
name = "reddw"
version = "0.1.0"
description = "A wallpaper changer"
authors = ["Liran Piade"]
license = ""
repository = ""
default-run = "reddw"
edition = "2021"
rust-version = "1.57"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.0.4", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.0.5", features = ["api-all"] }
libsqlite3-sys = { version = "^0", features = [ "bundled"] }
diesel = { version = "2.0.0", features = ["sqlite"] }
window-vibrancy = "0.1.3"
rand = "0.8.4"
ts-rs = {version = "^6.1", features = ["serde-compat"] }

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = [ "custom-protocol" ]
# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = [ "tauri/custom-protocol" ]

[profile.release]
strip = true 
