
[package]
name = "reddw_ui"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { version = "0.20.0", features = ["csr"] }
reddw_shared = { path = "../shared" }
web-sys = "0.3.61"

wasm-bindgen = {version = "0.2.84", features= ["serde", "serde_json"] }
js-sys = "0.3.61"
wasm-bindgen-futures = "0.4.34"
